#load pckgs
library(tidyverse)
library(maps)
library(rnaturalearth)
library(rnaturalearthdata)
library(viridis)
library(knitr)
library(kableExtra)
library(webshot)
library(htmlwidgets)
library(patchwork)
