---
title: "Final Report"
subtitle: |
  | Final Project 
  | Data Science 1 with R (STAT 301-1)
author: "Chau Tran"
pagetitle: "PM1 Chau Tran"
date: today

format:
  html:
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    link-external-newwindow: true

execute:
  warning: false
  echo: false

from: markdown+emoji
reference-location: margin
citation-location: margin
---
::: {.callout-tip icon=false}
## Github Repo Link

[Tran Chau's Final Project Github Repo](https://github.com/stat301-1-2024-fall/final-project-1-bunmam-ctrl.git)

:::

```{r}
#| label: load pck
library(tidyverse)
library(maps)
library(rnaturalearth)
library(rnaturalearthdata)
library(viridis)
library(sf)
library(patchwork)

```

```{r}
#| label: convert data 
abortion <- read_csv("data/global_abortion_raw.csv")|>
  janitor::clean_names()

violence <-  read_csv("data/violence_raw.csv")|>
  janitor::clean_names()
#gender_inequality
gender_inequality <-  read_csv("data/gender_inequality_index.csv")|>
  janitor::clean_names()

# Load world map with ISO codes
world_map <- ne_countries(scale = "medium", returnclass = "sf")


```

```{r}
#| label: tidy_violence - add iso to violence
#| results: false

#add iso to violence
violence_tidy <- violence|>
  mutate( iso = case_when(
    country %in% "Afghanistan" ~ "004", country %in% "Albania" ~ "008",
    country %in% "Angola" ~ "024", country %in% "Armenia" ~ "051",
    country %in% "Azerbaijan" ~ "031", country %in% "Bangladesh" ~ "050",
    country %in% "Benin" ~ "204", country %in% "Bolivia" ~ "068",
    country %in% "Burkina Faso" ~ "854", country %in% "Burundi" ~ "108",
    
    country %in% "Cambodia" ~ "116", country %in% "Cameroon" ~ "120",
    country %in% "Chad" ~ "148", country %in% "Colombia" ~ "170",
    country %in% "Comoros" ~ "174", country %in% "Congo" ~ "178",
    country %in% "Congo Democratic Republic" ~ "180", country %in% "Cote d'Ivoire" ~ "384",
    country %in% "Dominican Republic" ~ "214", country %in% "Egypt" ~ "818",
    
    country %in% "Eritrea" ~ "232", country %in% "Eswatini" ~ "748",
    country %in% "Ethiopia" ~ "231", country %in% "Gabon" ~ "266",
    country %in% "Gambia" ~ "270", country %in% "Ghana" ~ "288",
    country %in% "Guatemala" ~ "320", country %in% "Guinea" ~ "324",
    country %in% "Guyana" ~ "328", country %in% "Guyana" ~ "332",
    
    country %in% "Honduras" ~ "340", country %in% "India" ~ "356",
    country %in% "Indonesia" ~ "360", country %in% "Jordan" ~ "400",
    country %in% "Kenya" ~ "404", country %in% "Kyrgyz Republic" ~ "417",
    country %in% "Lesotho" ~ "426", country %in% "Liberia" ~ "430",
    country %in% "Madagascar" ~ "450", country %in% "Malawi" ~ "454",
    
    country %in% "Maldives" ~ "462", country %in% "Mali" ~ "466",
    country %in% "Moldova" ~ "498", country %in% "Morocco" ~ "504",
    country %in% "Mozambique" ~ "508", country %in% "Myanmar" ~ "104",
    country %in% "Namibia" ~ "516", country %in% "Nepal" ~ "524",
    country %in% "Nicaragua" ~ "558", country %in% "Niger" ~ "562",
    
    country %in% "Nigeria" ~ "566", country %in% "Pakistan" ~ "586",
    country %in% "Peru" ~ "604", country %in% "Philippines" ~ "608",
    country %in% "Rwanda" ~ "646", country %in% "Sao Tome and Principe" ~ "678",
    country %in% "Senegal" ~ "686", country %in% "Sierra Leone" ~ "694",
    country %in% "South Africa" ~ "710", country %in% "Tajikistan" ~ "762",
    
    country %in% "Tanzania" ~ "834", country %in% "Timor-Leste" ~ "626",
    country %in% "Togo" ~ "768", country %in% "Turkey" ~ "792",
    country %in% "Turkmenistan" ~ "795", country %in% "Uganda" ~ "800",
    country %in% "Ukraine" ~ "804", country %in% "Yemen" ~ "887",
    country %in% "Zambia" ~ "894", country %in% "Zimbabwe" ~ "716"
  ),
  .after = country
  )
 
```

```{r}
#| label: tidy_violence- modify justify violence and percent agree
#| results: false
#Modify justify violence and percent agree
violence_tidy <- violence_tidy|>
  mutate(
    justify_violence = as.factor(question),
    justify_violence = fct_recode(justify_violence, 
      "Household Mistake" = "... if she burns the food",
      "Marital Conflict" = "... if she argues with him",
      "Autonomy Violation" = "... if she goes out without telling him",
      "Intimacy Denial" = "... if she refuses to have sex with him",
      "Parental Neglect" = "... if she neglects the children",
      "With Reason" = "... for at least one specific reason",
    ),
    .before = value
  )|>
  rename("value_agree" = value)|>
  select(!question)

```


```{r}
#| label: tidy_violence - add subregion
#| results: false
# add subregion

sub_1 <- c("Afghanistan", "India", "Kyrgyz Republic", "Maldives",
                                 "Nepal", "Pakistan", "Tajikistan", "Turkmenistan")
sub_2 <-  c("Angola", "Benin", "Burkina Faso", "Burundi" , "Cameroon",
                           "Chad", "Comoros", "Congo", "Congo Democratic Republic",
                           "Cote d'Ivoire", "Eswatini", "Ethiopia", "Gabon", "Gambia",
                           "Ghana", "Guinea", "Kenya", "Lesotho", "Liberia", "Madagascar",
                           "Malawi", "Mali", "Mozambique", "Namibia", "Niger", "Nigeria",
                           "Rwanda", "Sao Tome and Principe", "Senegal", "Sierra Leone",
                           "South Africa", "Tanzania", "Togo", "Uganda", "Zambia",
                           "Zimbabwe")
sub_3 <- c("Armenia", "Azerbaijan", "Egypt", "Jordan",
                                         "Yemen")

sub_4 <- c("Bangladesh", "Cambodia", "Indonesia", "Myanmar",
                                     "Philippines", "Timor-Leste")
sub_5 <- c("Bolivia", "Colombia","Dominican Republic", "Guatemala", "Guyana",
                     "Honduras", "Nicaragua", "Peru")
sub_6 <- c("Albania", "Moldova", "Ukraine")


violence_tidy <- violence_tidy|>
  mutate( subregion = case_when(
    country %in% sub_1  ~ "Central and Southern Asia",
    country %in% sub_2 ~ "Sub-Saharan Africa",
    country %in% sub_3 ~ "Western Asia and Northern Africa",
    country %in% sub_4 ~ "Eastern and Southeastern Asia",
    country %in% sub_5  ~ "Latin America",
    country %in% sub_6  ~ "Europe and Northern America"
  ),
  .after = iso,
  subregion = as.factor(subregion)
  )

```


```{r}
#| label: tidy_violence - add abortion
#| results: false

#add abortion (legal relax, legal strict, illegal)
legal_request <-  c("Albania", "Moldova", "Armenia",
                    "Ukraine", "Bolivia",    "Azerbaijan",
                         "Colombia", "Guyana", "Cambodia",
                         "Nepal", "Kyrgyz Republic",
                         "South Africa","Mozambique", "Tajikistan")
      

legal_reason<- c("Ethiopia", "Ghana", "Zambia",
                  "Rwanda" , "Gabon", "India", "Namibia",
                   "Indonesia", "Philippines", "Timor-Leste",
                  "Peru", "Guatemala", "Honduras", "Nicaragua", "Turkmenistan",
                 "Kenya", "Guinea", "Liberia", "Bangladesh")

illegal <-  c("Angola", "Burkina Faso", "Benin","Lesotho", "Madagascar",
              "Burundi", "Chad", "Comoros", "Congo", "Egypt",  "Jordan",
               "Congo Democratic Republic", "Niger", "Tanzania",
               "Nigeria", "Sao Tome and Principe", "Gambia",
              "Senegal", "Sierra Leone", "Togo", "Eswatini", "Myanmar",
              "Uganda", "Zimbabwe","Cote d'Ivoire", "Malawi", "Mali",
              "Afghanistan", "Pakistan", "Yemen", "Maldives" , "Cameroon", "Dominican Republic")

     

violence_tidy <- violence_tidy|>
  mutate( abortion_access = case_when(
    country %in% legal_request  ~ "Legal on Request",
    country %in% legal_reason ~"Legal for Specific Reasons",
    country %in% illegal ~ "Illegal or Extremely Restricted"
  ),
  abortion_access = as.factor(abortion_access)
  )


                                               
```

```{r}
#| label: tidy abortion 

abortion_tidy <- abortion|>
  mutate(iso = str_pad(iso, width = 3, pad = "0"))|>
  select(country,iso, region, subregion,numberofabortions, abortionrate) |>
  rename(
    "number_of_abortion" = "numberofabortions",
    "abortion_rate" = "abortionrate"
  )

```



```{r}
#| label: tidy gender inequality 

gender_inequality_tidy <-  gender_inequality|>
  mutate(undp_developing_regions = 
    case_when(
      undp_developing_regions %in% "SSA" ~ "Sub-Saharan Africa",
      undp_developing_regions %in% "LAC" ~ "Latin America and the Caribbean",
      undp_developing_regions %in% "EAP" ~ "East Asia and the Pacific",
      undp_developing_regions %in% "AS" ~ "Arab States",
      undp_developing_regions %in% "ECA" ~ "Europe and Central Asia",
      undp_developing_regions %in% "SA" ~ "South Asia"
    )
  )
```


```{r}
#| label:  Global Number of Abortion Map (Graph 1)
#| fig-cap: "Global Number of Abortions by Country"

#calc count of abortion
abortion_n <- abortion_tidy|>
  count(iso, wt = number_of_abortion)|>
  mutate(iso = as.character(iso))

# Join the map with abortion_tidy data by ISO codes
map_abortion<- world_map|>
  left_join(abortion_n, join_by("iso_n3" == "iso"))

#Graph

ggplot(map_abortion) +
  geom_sf(aes(fill = n), color = "black", size = 10.0) +
  scale_fill_viridis_c( na.value = "grey80", name = "Number of Cases") +
  theme_minimal() +
  labs(
    title = "Global Abortion Incidence from 1990 to 2018",
    subtitle = "A comprehensive mapping of abortion cases reported by country, \n highlighting variations and trends over 28 years",
    fill = "Proportion"
  )+
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(face = "italic", hjust = 0.5),
    axis.title = element_text(size = 14),
    axis.text.x = element_text(size = 12, angle = 45, hjust = 1),
    axis.text.y = element_text(size = 12),
    legend.title = element_text(face = "bold")
  )

```
```{r}
#| label:  Gender Index Global Map Map (Graph 2)
#| fig-cap: "Global Number of Abortions by Country"

# Join the map with gender_equality data by ISO codes
map_gender <- world_map|>
  left_join(gender_inequality_tidy, join_by("iso_a3" == "iso3"))

#Graph

ggplot(map_gender) +
  geom_sf(aes(fill = gender_inequality_index_2018), color = "black", size = 10.0) +
  scale_fill_viridis_c( na.value = "grey80", name = "Number of Cases") +
  theme_minimal() +
  labs(
    title = "Global Gender Equality Index by Country in 2018",
    subtitle = "A geographical representation of gender equality,\n measuring disparities in various social, economic, and political areas.",
    fill = "Gender Index"
  )+
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(face = "italic", hjust = 0.5),
    axis.title = element_text(size = 14),
    axis.text.x = element_text(size = 12, angle = 45, hjust = 1),
    axis.text.y = element_text(size = 12),
    legend.title = element_text(face = "bold")
  )

```
```{r}
#| label: Top 5 global gender equality index

top_5_gender_inequality <- gender_inequality_tidy|>
  slice_max(n =5, order_by = gender_inequality_index_2021, with_ties = TRUE)|> 
  select(country, undp_developing_regions, gender_inequality_index_2021,hdi_rank_2021)|>
  rename(
    "Country" = country,
    "Subregions"= undp_developing_regions,
    "Human Development Index Rank" = hdi_rank_2021,
    "Gender Inequality Index" = gender_inequality_index_2021
  )

knitr::kable(top_5_gender_inequality)
```


```{r}
#| label: The accessibility of abortion in (Western Asia and Africa) (Graph 3a)

# Join the map with violence_tidy data by ISO codes
map_data_2 <- world_map|>
  
  left_join(violence_tidy, join_by("iso_n3" == "iso"))
# Graph Western Asia and Africa
graph_africa <- map_data_2|>
  filter(subregion.x %in%  c("Western Asia", "Northern Africa","Eastern Africa", "Western Africa", 
                             "Southern Africa", "Middle Africa"))|>
  ggplot()+
  geom_sf(aes(fill = abortion_access), color = "black", size = 0.1) +
  theme_minimal() +
  labs(
    subtitle = "Western Asia and Africa",
  ) +
  theme(
    plot.subtitle = element_text(size = 10, hjust = 0.5),
    axis.title = element_blank(),
    axis.text = element_blank(),
    legend.position = "none"
  )


```

```{r}
#| label: The accessibility of abortion in developing countries (Eastern and Southeastern Asia, Graph 3b)
# Graph Central, South, and Southeastern Asia

graph_asia <- map_data_2|>
  filter(subregion.x %in%  c("South-Eastern Asia", "Southern Asia",
                             "Central Asia", "Southern Asia"))|>
  ggplot()+
  geom_sf(aes(fill = abortion_access), color = "black", size = 0.1) +
  theme_minimal() +
  coord_sf(xlim = c(40, 160), ylim = c(-10, 45)) +
  labs(
    subtitle = "Central, South, and Southeastern Asia"
  ) +
  theme(
    plot.subtitle = element_text(size = 10, hjust = 0.5),
    axis.title = element_blank(),
    axis.text = element_blank(),
    legend.position = "none"
  )


```


```{r}
#| label: The accessibility of abortion in developing countries (Latin America, Graph 3c)
# Graph Latin America
graph_latin_america <-  map_data_2|>
  filter(subregion.x %in%  c("South America", "Central America", "Caribbean"))|>
  ggplot()+
  geom_sf(aes(fill = abortion_access), color = "black", size = 0.1) +
  theme_minimal() +
  labs(
    subtitle = "Latin America"
  ) +
  coord_sf(xlim = c(-100, -30), ylim = c(-30, 20)) +
  theme(
    plot.subtitle = element_text(size = 10, hjust = 0.5),
    axis.title = element_blank(),
    axis.text = element_blank(),
    legend.position = "bottom",
    legend.title = element_text(face = "bold")
  )


```


```{r}
#| label: The accessibility of abortion (Europe, Graph 3d)

# Graph Europe 
graph_europe <-  map_data_2|>
  filter(subregion.x %in%  c("Eastern Europe", "Southern Europe" ))|>
  ggplot()+
  geom_sf(aes(fill = abortion_access), color = "black", size = 0.1) +
  coord_sf(xlim = c(10, 40), ylim = c(40, 60))  +
  theme_minimal() +
  labs(
    subtitle = "Europe"
  ) +
  theme(
    plot.subtitle = element_text(size = 10, hjust = 0.5),
    axis.title = element_blank(),
    axis.text = element_blank(),
    legend.position = "none"
  )

```

```{r}
#| label: Constructing Graph 3
#| fig-cap: Justifications for Violence by Region

# Define a consistent color scale
abortion_color_scale <- scale_fill_manual(
  values = c(
    "Illegal or Extremely Restricted" = "darkblue",
    "Legal for Specific Reasons" = "deeppink3",
    "Legal on Request" = "yellow",
    "NA" = "grey80"
  ),
  name = "Abortion\nAccess",
  labels = c(
    "Illegal or\nExtremely Restricted",
    "Legal for\nSpecific Reasons",
    "Legal on\nRequest",
    "NA"
  )  
)


# Update all graphs to use the same color scale
graph_africa <- graph_africa +
  abortion_color_scale 
  
graph_asia <- graph_asia +
  abortion_color_scale 
 

graph_latin_america <- graph_latin_america +
  abortion_color_scale 

graph_europe <- graph_europe +
  abortion_color_scale 

# Combine the regional maps into a single layout
final_plot <- (graph_africa | graph_asia) / (graph_latin_america | graph_europe) +
  plot_annotation(
    title = "Abortion Accessibility in Developing Countries",
    theme = theme(
     plot.title = element_text(size = 16, face = "bold", hjust = 0.5),

  ))
  
final_plot
```




```{r}
#| label: Justification for Violence across subregions (Graph 4)
#| fig-cap: "Abortion Accessibility in Developing Countries"


#reorder the factor in descending order (justify_violence)
justify_totals <- violence_tidy|>
  group_by(justify_violence)|>
  summarise(total_value = sum(value_agree, na.rm = TRUE))|>
  arrange(desc(total_value))

violence_tidy$justify_violence <- factor(
  violence_tidy$justify_violence,
  levels = justify_totals$justify_violence
)

#reorder the factor in descending order (subregion)
subregion_totals <- violence_tidy|>
  group_by(subregion)|>
  summarise(total_value = sum(value_agree, na.rm = TRUE))|>
  arrange(desc(total_value))

violence_tidy$subregion <- factor(
  violence_tidy$subregion,
  levels = subregion_totals$subregion
)


#Making graphs
violence_count <- violence_tidy|>
  group_by( justify_violence)|>
  drop_na()|>
  ggplot(aes(x = justify_violence, y = value_agree, fill = subregion))+
  geom_col()+
  theme_minimal() +
  scale_fill_brewer(palette = "Dark2")+
  scale_x_discrete(labels = c("With\nReason", "Parental\nNeglect", "Autonomy\nViolation", 
                              "Marital\nConflict", "Intimacy\nDenial", "Household\nMistake"))+
  labs(
    title = "Regional Support for Various Toleration of Violence",
    subtitle = "Analysis of public opinion on different causes of violence \n across developing countries in 2020",
    x = NULL,
    y = "Number of People Supporting",
    fill = "Subregion"
  )+
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(face = "italic", hjust = 0.5),
    axis.title = element_text(size = 14),
    axis.text.x = element_text(size = 12, angle = 45, hjust = 1),
    axis.text.y = element_text(size = 12),
    legend.title = element_text(face = "bold")
  )
  
violence_count

```
```{r}
#| label: Justification for Violence in each category and subregions (Table 2) 
#| tbl-cap: "Comparative Data on Justifications for Violence by Region"
violence_subregion_category <-violence_tidy|>
  group_by(subregion, justify_violence)|>
  summarise(total_value = round(sum(value_agree, na.rm = TRUE)),
            )|>
  drop_na()|>
  pivot_wider(
    names_from = subregion,
    values_from = total_value
  )|>
  rename(
    "Justification for Violence" = justify_violence 
  )

knitr::kable(violence_subregion_category)

```

